spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL

server:
  servlet:
    context-path: /canismajor
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org:
      springframework: INFO
