server:
  port: 8906

spring:
  datasource:
    url: jdbc:postgresql://pgsql/universe?currentSchema=canismajor
    username: postgres
    password: 123456

site:
  andromeda: http://universe-andromeda:8906/andromeda
